const fs = require('fs');
const path = require('path');

const sourceDir = path.join(__dirname, '../Yapılan_işler_bölümü');
const destDir = path.join(__dirname, '../public/images/gallery');
const dataFile = path.join(__dirname, '../src/data/gallery.ts');

async function processGallery() {
  if (!fs.existsSync(destDir)) {
    fs.mkdirSync(destDir, { recursive: true });
  }

  const files = fs.readdirSync(sourceDir);
  const imageFiles = files.filter(f => f.match(/\.(jpg|jpeg|png|gif|webp)$/i));
  
  const galleryData = [];
  
  let count = 1;
  for (const file of imageFiles) {
    const ext = path.extname(file).toLowerCase();
    const newName = `gallery-${count}${ext}`;
    
    const sourcePath = path.join(sourceDir, file);
    const destPath = path.join(destDir, newName);
    
    fs.copyFileSync(sourcePath, destPath);
    
    galleryData.push({
      id: count.toString(),
      src: `/images/gallery/${newName}`,
      alt: `Kılıçarslan Perde Tasarım Uygulaması ${count}`
    });
    
    count++;
  }
  
  const dataContent = `// Automatically generated by scripts/process-gallery.js
export interface GalleryImage {
  id: string;
  src: string;
  alt: string;
}

export const galleryImages: GalleryImage[] = ${JSON.stringify(galleryData, null, 2)};
`;

  fs.writeFileSync(dataFile, dataContent);
  console.log(`Processed ${imageFiles.length} images successfully.`);
}

processGallery().catch(console.error);
