// Automatically generated by scripts/process-gallery.js
export interface GalleryImage {
  id: string;
  src: string;
  alt: string;
}

export const galleryImages: GalleryImage[] = [
  {
    "id": "1",
    "src": "/images/gallery/gallery-1.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 1"
  },
  {
    "id": "2",
    "src": "/images/gallery/gallery-2.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 2"
  },
  {
    "id": "3",
    "src": "/images/gallery/gallery-3.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 3"
  },
  {
    "id": "4",
    "src": "/images/gallery/gallery-4.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 4"
  },
  {
    "id": "5",
    "src": "/images/gallery/gallery-5.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 5"
  },
  {
    "id": "6",
    "src": "/images/gallery/gallery-6.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 6"
  },
  {
    "id": "7",
    "src": "/images/gallery/gallery-7.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 7"
  },
  {
    "id": "8",
    "src": "/images/gallery/gallery-8.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 8"
  },
  {
    "id": "9",
    "src": "/images/gallery/gallery-9.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 9"
  },
  {
    "id": "10",
    "src": "/images/gallery/gallery-10.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 10"
  },
  {
    "id": "11",
    "src": "/images/gallery/gallery-11.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 11"
  },
  {
    "id": "12",
    "src": "/images/gallery/gallery-12.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 12"
  },
  {
    "id": "13",
    "src": "/images/gallery/gallery-13.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 13"
  },
  {
    "id": "14",
    "src": "/images/gallery/gallery-14.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 14"
  },
  {
    "id": "15",
    "src": "/images/gallery/gallery-15.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 15"
  },
  {
    "id": "16",
    "src": "/images/gallery/gallery-16.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 16"
  },
  {
    "id": "17",
    "src": "/images/gallery/gallery-17.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 17"
  },
  {
    "id": "18",
    "src": "/images/gallery/gallery-18.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 18"
  },
  {
    "id": "19",
    "src": "/images/gallery/gallery-19.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 19"
  },
  {
    "id": "20",
    "src": "/images/gallery/gallery-20.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 20"
  },
  {
    "id": "21",
    "src": "/images/gallery/gallery-21.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 21"
  },
  {
    "id": "22",
    "src": "/images/gallery/gallery-22.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 22"
  },
  {
    "id": "23",
    "src": "/images/gallery/gallery-23.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 23"
  },
  {
    "id": "24",
    "src": "/images/gallery/gallery-24.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 24"
  },
  {
    "id": "25",
    "src": "/images/gallery/gallery-25.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 25"
  },
  {
    "id": "26",
    "src": "/images/gallery/gallery-26.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 26"
  },
  {
    "id": "27",
    "src": "/images/gallery/gallery-27.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 27"
  },
  {
    "id": "28",
    "src": "/images/gallery/gallery-28.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 28"
  },
  {
    "id": "29",
    "src": "/images/gallery/gallery-29.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 29"
  },
  {
    "id": "30",
    "src": "/images/gallery/gallery-30.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 30"
  },
  {
    "id": "31",
    "src": "/images/gallery/gallery-31.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 31"
  },
  {
    "id": "32",
    "src": "/images/gallery/gallery-32.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 32"
  },
  {
    "id": "33",
    "src": "/images/gallery/gallery-33.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 33"
  },
  {
    "id": "34",
    "src": "/images/gallery/gallery-34.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 34"
  },
  {
    "id": "35",
    "src": "/images/gallery/gallery-35.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 35"
  },
  {
    "id": "36",
    "src": "/images/gallery/gallery-36.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 36"
  },
  {
    "id": "37",
    "src": "/images/gallery/gallery-37.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 37"
  },
  {
    "id": "38",
    "src": "/images/gallery/gallery-38.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 38"
  },
  {
    "id": "39",
    "src": "/images/gallery/gallery-39.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 39"
  },
  {
    "id": "40",
    "src": "/images/gallery/gallery-40.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 40"
  },
  {
    "id": "41",
    "src": "/images/gallery/gallery-41.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 41"
  },
  {
    "id": "42",
    "src": "/images/gallery/gallery-42.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 42"
  },
  {
    "id": "43",
    "src": "/images/gallery/gallery-43.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 43"
  },
  {
    "id": "44",
    "src": "/images/gallery/gallery-44.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 44"
  },
  {
    "id": "45",
    "src": "/images/gallery/gallery-45.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 45"
  },
  {
    "id": "46",
    "src": "/images/gallery/gallery-46.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 46"
  },
  {
    "id": "47",
    "src": "/images/gallery/gallery-47.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 47"
  },
  {
    "id": "48",
    "src": "/images/gallery/gallery-48.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 48"
  },
  {
    "id": "49",
    "src": "/images/gallery/gallery-49.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 49"
  },
  {
    "id": "50",
    "src": "/images/gallery/gallery-50.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 50"
  },
  {
    "id": "51",
    "src": "/images/gallery/gallery-51.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 51"
  },
  {
    "id": "52",
    "src": "/images/gallery/gallery-52.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 52"
  },
  {
    "id": "53",
    "src": "/images/gallery/gallery-53.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 53"
  },
  {
    "id": "54",
    "src": "/images/gallery/gallery-54.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 54"
  },
  {
    "id": "55",
    "src": "/images/gallery/gallery-55.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 55"
  },
  {
    "id": "56",
    "src": "/images/gallery/gallery-56.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 56"
  },
  {
    "id": "57",
    "src": "/images/gallery/gallery-57.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 57"
  },
  {
    "id": "58",
    "src": "/images/gallery/gallery-58.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 58"
  },
  {
    "id": "59",
    "src": "/images/gallery/gallery-59.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 59"
  },
  {
    "id": "60",
    "src": "/images/gallery/gallery-60.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 60"
  },
  {
    "id": "61",
    "src": "/images/gallery/gallery-61.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 61"
  },
  {
    "id": "62",
    "src": "/images/gallery/gallery-62.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 62"
  },
  {
    "id": "63",
    "src": "/images/gallery/gallery-63.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 63"
  },
  {
    "id": "64",
    "src": "/images/gallery/gallery-64.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 64"
  },
  {
    "id": "65",
    "src": "/images/gallery/gallery-65.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 65"
  },
  {
    "id": "66",
    "src": "/images/gallery/gallery-66.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 66"
  },
  {
    "id": "67",
    "src": "/images/gallery/gallery-67.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 67"
  },
  {
    "id": "68",
    "src": "/images/gallery/gallery-68.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 68"
  },
  {
    "id": "69",
    "src": "/images/gallery/gallery-69.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 69"
  },
  {
    "id": "70",
    "src": "/images/gallery/gallery-70.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 70"
  },
  {
    "id": "71",
    "src": "/images/gallery/gallery-71.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 71"
  },
  {
    "id": "72",
    "src": "/images/gallery/gallery-72.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 72"
  },
  {
    "id": "73",
    "src": "/images/gallery/gallery-73.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 73"
  },
  {
    "id": "74",
    "src": "/images/gallery/gallery-74.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 74"
  },
  {
    "id": "75",
    "src": "/images/gallery/gallery-75.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 75"
  },
  {
    "id": "76",
    "src": "/images/gallery/gallery-76.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 76"
  },
  {
    "id": "77",
    "src": "/images/gallery/gallery-77.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 77"
  },
  {
    "id": "78",
    "src": "/images/gallery/gallery-78.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 78"
  },
  {
    "id": "79",
    "src": "/images/gallery/gallery-79.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 79"
  },
  {
    "id": "80",
    "src": "/images/gallery/gallery-80.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 80"
  },
  {
    "id": "81",
    "src": "/images/gallery/gallery-81.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 81"
  },
  {
    "id": "82",
    "src": "/images/gallery/gallery-82.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 82"
  },
  {
    "id": "83",
    "src": "/images/gallery/gallery-83.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 83"
  },
  {
    "id": "84",
    "src": "/images/gallery/gallery-84.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 84"
  },
  {
    "id": "85",
    "src": "/images/gallery/gallery-85.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 85"
  },
  {
    "id": "86",
    "src": "/images/gallery/gallery-86.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 86"
  },
  {
    "id": "87",
    "src": "/images/gallery/gallery-87.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 87"
  },
  {
    "id": "88",
    "src": "/images/gallery/gallery-88.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 88"
  },
  {
    "id": "89",
    "src": "/images/gallery/gallery-89.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 89"
  },
  {
    "id": "90",
    "src": "/images/gallery/gallery-90.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 90"
  },
  {
    "id": "91",
    "src": "/images/gallery/gallery-91.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 91"
  },
  {
    "id": "92",
    "src": "/images/gallery/gallery-92.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 92"
  },
  {
    "id": "93",
    "src": "/images/gallery/gallery-93.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 93"
  },
  {
    "id": "94",
    "src": "/images/gallery/gallery-94.jpeg",
    "alt": "Kılıçarslan Perde Tasarım Uygulaması 94"
  }
];
